#ifndef _VL53L9_TRANSFORM_C_VERSION_H_
#define _VL53L9_TRANSFORM_C_VERSION_H_

#define VL53L9_TRANSFORM_C_VERSION "0.4.0"
#define VL53L9_TRANSFORM_C_VERSION_MAJOR 0
#define VL53L9_TRANSFORM_C_VERSION_MINOR 4
#define VL53L9_TRANSFORM_C_VERSION_PATCH 0

#endif // _VL53L9_TRANSFORM_C_VERSION_H_
